#!/usr/bin/env bash

. /common

RETAIN="${RETAIN:-5}"
RETAIN_STR="$(for ((i=0;i<RETAIN;i++)); do echo -n O; done)"

cd "$trg"

( set -x; rm -rf *%$RETAIN_STR*; )

printf "%s\n" */ |
  sed 's|/$||' |
  egrep "$namesep"'O+$' |
  sort -t"%" -k2 -r |
  while read d; do ( set -x; mv "$d" "${d}O"; ); done

latest_trg="$trg/$(name_prefix)${namesep}O"
(
  set -x;
  if ! cp -al *${namesep}OO "$latest_trg"; then mkdir -p "$latest_trg"; fi
  rsync -a --delete --include='*/' --exclude='*' "$src/" "$latest_trg"
)
