#!/usr/bin/env bash

. /common

numClients="$1"
clientNum="$2"

echo "numClients: $numClients, clientNum: $clientNum"

set -e

latest_trg="$(get_latest_trg)"

cd "$src"

cd nexus

files_to_backup=($(ls -A | grep -v '^blobs$' | awk "NR%$numClients==$clientNum"))

for myContent in ${files_to_backup[@]}; do
  ( set -x; rsync -s -ah --delete --numeric-ids "$myContent" $latest_trg/nexus; )
done

cd blobs

for d in */; do
  (
    cd "$d"
    for f in $(ls -A | grep -v '^content$' | awk "NR%$numClients==$clientNum"); do
      ( set -x; rsync -s -ah --delete --numeric-ids "$f" "$latest_trg/nexus/blobs/$d/"; )
    done

    cd content
    for x in $(ls -A | awk "NR%$numClients==$clientNum"); do
      ( set -x; rsync -s -ah --delete --numeric-ids "$x" "$latest_trg/nexus/blobs/$d/content/"; )
    done
  )
done

